version: "3.4"
services:
  CallService:
    container_name: call_service
    tty: true
    image: f3eb2848a4b8
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres:
